@startuml ModelDeploymentStrategy
' ──────────────────────  visual settings  ──────────────────────
skinparam defaultTextAlignment center
skinparam node {
  BackgroundColor White
  BorderColor Black
}
skinparam arrow {
  Color Black
}

header
Model Deployment Strategie
endheader

' ──────────────────────  decision flow  ────────────────────────
start

if ("Patienten-kritische\n Entscheidung?") then (Ja)
  if ("Physik des Objekts\n ausreichend verstanden?") then (Ja)
    :Physikmodell;
    note left
      + White Box Insight
      + interpretierbar
      + Twin Sync Fähigkeit
    end note
  else (Nein)
    #orange:PINN;
    note right
      + Bessere Generalisierung
        bei sparse/noisy Daten
      - computational constraints
        bei digital Computer
    end note
  endif
else (Nein)
  if ("Pattern recognition\nmit anschließender\nProzessaktivierung?\n('AI as a Sensor')") then (Ja)
    split
      #orange:PINN;
    split again
      #orange:SLM;
    end split
  else (Nein)
    :Keine AI Verwendung;
    note right
       andere Methoden
       patientenorientiert
       nicht risikovertretbar:
       - Cloud-Ausfall
       - Systemüberlastung
       - AI Blackbox (u.a. biasing)
    end note
  endif
endif

if (improve PINN insight?) then (Ja)
  #orange:PINN + SLM;
  note left
    add PINN to a SLM domain (z.B. japanisch / deutsch) language model
    its like giving a child (SLM) a tool (PINN) to handle and explore its behaviour
  end note
else (Nein)
endif

stop

skinparam LegendBackgroundColor #FFFFFF
skinparam LegendBorderColor #FFFFFF

legend right
  <#FFFFFF,#FFFFFF>|<#orange>| <size:24>AIoT</size> |
endlegend

@enduml
