@startuml PINNPhysicState
skinparam Linetype ortho
left to right direction

header
Links zwischen Physikmodell und PINN
endheader

package Physikmodell_Approach {
  class Physikmodell {
    C++ basiert
  }
}

package PINN_Approach {
  class PINN {
    C++ basiert
  }

  class PinnTrainer {
    Python basiert
  }

  note right of PinnTrainer
    Python module uses TensorFlow.
    The TensorFlow model is translated into an ONNX model.
  end note

  note right of PINN
    ONNX model used in C++ for inference.
  end note
}

PinnTrainer --> PINN
Physikmodell --o PINN
PINN --* Physikmodell

@enduml
